### ISSUE TITLE
The file 'pgettext.py' is redundant

### ISSUE THREAD

**Issue by yatinmaan** [sugarlabs/clock-activity#12]
I looked through the code and could not find where it is being used. (Is it?)
Even if it is I don't understand the need of this module when the same functionality is provided by sugar3.activity.i18n.pgettext().

**Comment by quozl** [comment]
Thanks for noticing that.

* first reference began in 5dc157569de2087873deb5af431767196dd175e6 (initial import of version 5),
* last reference removed in 8b9af018bde0b2910c731401cc0ba26283ba6adc (replace pgettext with gettext),

Fixed in https://github.com/sugarlabs/clock-activity/pull/13
