### ISSUE TITLE
Add Clock to Help

### ISSUE THREAD

**Issue by quozl** [sugarlabs/clock-activity#20]
Clock has no documentation in help.sugarlabs.org, the Sugar embedded Help, or the Help activity.

- [x] write a `source/clock.rst`,
- [x] update `source/index.rst`,
- [x] update `helplink.json`,
- [x] make pull requests to https://github.com/godiard/help-activity

Information sources for writing;
* http://wiki.sugarlabs.org/go/Activities/Clock
* http://wiki.laptop.org/go/Clock_activity
* https://github.com/sugarlabs/clock-activity/blob/master/README.md

Lesson plan ideas;
* reading the time in different ways,
* speaking the time,
* ticking clocks, new feature in 6b4223d,
* on some systems, the download time button which uses NTP,
* combination of above.

**Comment by EmilyOng** [comment]
i would like to take this issue

**Comment by quozl** [comment]
Thanks!

**Comment by EmilyOng** [comment]
https://github.com/godiard/help-activity/pull/37

- [x] write a source/clock.rst,
- [x] update source/index.rst,
- [x] update helplink.json,
- [x] make pull requests to https://github.com/godiard/help-activity
- [x] added images

Lesson plans:

- [x] learning to count time
- [x] reading time in different ways
- [x] speaking time
- [x] learning about angles
- [x] finding the geographical north or south

**Comment by quozl** [comment]
Thanks.
